name: py37-pytorch
channels:
  - conda-forge
  - pytorch
  - dglteam
dependencies:
  - python=3.7
  - pip
  - numpy
  - matplotlib
  - jupyter
  - jupyterlab
  - pytorch
  - torchvision
  - torchtext
  - nb_conda_kernels
  - dgl>=0.4.3
  - pip:
    - torchviz
